
# fastq okuma işlemi
fastq_file <- "data/barcode77.fastq.gz"
cat("R Pipeline Started: Reading FASTQ file...\n")

con <- gzfile(fastq_file, "rt")
lines <- readLines(con)
close(con)

# metrikleri hesaplama işlemi
cat("Calculating metrics (Length, GC, Quality)...\n")
seq_lines <- lines[seq(2, length(lines), by=4)]
qual_lines <- lines[seq(4, length(lines), by=4)]

# uzunluk 
read_lengths <- nchar(seq_lines)

# ortalama İstatistikler
mean_length <- mean(read_lengths)
median_length <- median(read_lengths)

# özet raporu
cat("\n=========================================================\n")
cat("   EXECUTIVE SUMMARY(özet raporu) (GENERATED BY R)   \n")
cat("===========================================================\n")
cat("Total Reads Processed :", length(seq_lines), "\n")
cat("Mean Read Length      :", round(mean_length, 2), "bp\n")
cat("Median Read Length    :", round(median_length, 2), "bp\n")
cat("===========================================================\n")
cat("R Pipeline execution completed successfully.\n")